const throwError = (): never => {
   throw new Error('This is a test error for logging!');
};

export default throwError;